name: Deploy Production

on:
  push:
    branches:
      - main

jobs:
  translate:
    runs-on: ubuntu-latest
    steps:
      - name: Generate translations
        uses: lyqht/deepl-translate-github-action@v2.1.1
        with:
          target_languages: pt-PT,pt-BR,zh,fr,ja,ko,pl,ru,de,fi,id,it,nl,es
          input_file_path: public/locales/en/translation.json
          output_file_name_pattern: public/locales/{language}/translation.json
          deepl_api_key: ${{ secrets.DEEPL_API_KEY }}
  deploy:
    needs: [translate]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Install Dependencies
        run: pnpm install --no-frozen-lockfile
      - name: Build App
        run: pnpm build
      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
